const fs = require('fs');

let file = 'src/pages/Appointments.js';
let content = fs.readFileSync(file, 'utf8');

// Add "Completed" to the dropdown options for modify
content = content.replace(
  '<option>Consultation</option>',
  '<option>Consultation</option>\n                <option>Completed</option>'
);

// We need a status dropdown in "Modify"!
// Wait, currently status is just "Pending", "Confirmed", "Cancelled". Let's add a separate status field in the form.

const statusField = `
          <div className="space-y-2">
            <label className="text-sm font-medium text-text-dark">
              Status
            </label>
            <select 
              value={formData.status}
              onChange={(e) => setFormData({...formData, status: e.target.value})}
              className="w-full bg-bg-main border border-border-light rounded-md px-3 py-2 text-sm focus:outline-none focus:border-primary text-text-dark">
              <option value="Pending">Pending</option>
              <option value="Confirmed">Confirmed</option>
              <option value="Completed">Completed</option>
              <option value="Cancelled">Cancelled</option>
            </select>
          </div>
`;

content = content.replace(
  '<div className="space-y-2">\n            <label className="text-sm font-medium text-text-dark">\n              Notes (Optional)',
  statusField + '\n          <div className="space-y-2">\n            <label className="text-sm font-medium text-text-dark">\n              Notes (Optional)'
);

// Add price state and modal
content = content.replace(
  'const [isCancelConfirmOpen, setIsCancelConfirmOpen] = useState(false);',
  'const [isCancelConfirmOpen, setIsCancelConfirmOpen] = useState(false);\n  const [isPriceModalOpen, setIsPriceModalOpen] = useState(false);\n  const [servicePrice, setServicePrice] = useState("");'
);

// Update save logic
const saveLogicTarget = `    } else {
      setAppointmentsData(appointmentsData.map(a => a.id === selectedAppointment.id ? { ...a, ...formData } : a));
      addToast(\`Appointment updated for \${formData.patient}.\`);
    }
    setIsModalOpen(false);`;

const newSaveLogic = `    } else {
      if (formData.status === "Completed" && selectedAppointment.status !== "Completed") {
         // Ask for price
         setIsModalOpen(false);
         setIsPriceModalOpen(true);
         return; // wait for price modal closing
      }
      setAppointmentsData(appointmentsData.map(a => a.id === selectedAppointment.id ? { ...a, ...formData } : a));
      addToast(\`Appointment updated for \${formData.patient}.\`);
    }
    setIsModalOpen(false);`;

content = content.replace(saveLogicTarget, newSaveLogic);

// Add function to save price
const confirmPriceLogic = `
  const handleSaveCompletedAppointment = () => {
     setIsPriceModalOpen(false);
     setAppointmentsData(appointmentsData.map(a => a.id === selectedAppointment.id ? { ...a, ...formData, price: servicePrice } : a));
     addToast(\`Appointment for \${formData.patient} marked as Completed. Revenue added: \$\${servicePrice}.\`, "success");
     setServicePrice("");
  };
`;

content = content.replace(
  'const renderCalendarView = () => {',
  confirmPriceLogic + '\n  const renderCalendarView = () => {'
);


// Add Price Modal JSX
const priceModalJsx = `
      <Modal
        isOpen={isPriceModalOpen}
        onClose={() => setIsPriceModalOpen(false)}
        title="Appointment Completed - Enter Price"
        footer={
          <>
            <Button variant="ghost" onClick={() => setIsPriceModalOpen(false)}>Cancel</Button>
            <Button variant="primary" onClick={handleSaveCompletedAppointment}>Save Payment</Button>
          </>
        }>
        <div className="space-y-4">
           <p className="text-sm text-text-muted">The appointment has been checked out successfully. Please enter the fee generated by this visit to calculate total revenue.</p>
           <div className="space-y-2">
             <label className="text-sm font-medium text-text-dark">Service Fee ($)</label>
             <input type="number" min="0" step="0.01" value={servicePrice} onChange={e => setServicePrice(e.target.value)} className="w-full bg-bg-main border border-border-light rounded-md px-3 py-2 text-sm text-text-dark" placeholder="e.g. 150.00" />
           </div>
        </div>
      </Modal>
`;

content = content.replace(
  '<ConfirmDialog',
  priceModalJsx + '\n\n      <ConfirmDialog'
);

fs.writeFileSync(file, content);
